import type { Metadata } from "next";
import Header from "../app/components/Header";
import Footer from '../app/components/Footer';
import "./globals.css";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      <link href="https://fonts.googleapis.com/css2?family=Crisp+Aeonik+Pro&display=swap" rel="stylesheet"/>
      <link
            href="https://fonts.googleapis.com/css2?family=Crisp+Aeonik+Pro&display=swap"
            rel="stylesheet"
          />
      </head>
      <body>
        <Header />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
